apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoappqa
spec:
  ingressClassName: nginx
  rules:
  - host: qa.demoapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demofrontendqa
            port:
              number: 80